### ISSUE TITLE
Listing type of ML Problems and its types

### ISSUE THREAD

**Issue by RibhavKhanna** [iiitl/ML_tutorial#1]
### Update the readme.md file by adding various type of ML problems and its type. for E.g.
**Regression**
short dec

- Simple Linear Regression
- ...so on.
  
You can use the following link for help https://vitalflux.com/most-common-types-machine-learning-problems/

**Comment by RibhavKhanna** [comment]
Also, make updates before conclusion column an alsogive proper heading

**Comment by ADudhe01** [comment]
Hello @RibhavKhanna sir, I want to work on this issue.  Could you please assign it to me.

**Comment by Zhu-VISH** [comment]
Hi @RibhavKhanna I would like to work on this issue, please assign it to me.

**Comment by maskboyAvi** [comment]
Hello @RibhavKhanna , I want to work on this issue, can you please assign it to me.

**Comment by RibhavKhanna** [comment]
@ADudhe01 I have assigned you this issue

**Comment by dynamicdhxx** [comment]
Good Evening @RibhavKhanna i would like to work on this issue.
Kindly assign me.
