### ISSUE TITLE
Mathematical Operations

### ISSUE THREAD

**Issue by parth-verma7** [iiitl/ML_tutorial#17]
Using pandas library, calculate the mean mode, mode and median of Salary column of 'Salary' column of dataset.

**Comment by parth-verma7** [comment]
> hello @parth-verma7 sir ,I would like to work on this issue, please assign it to me.

@arshkatkar  You can start working upon this issue.

**Comment by maskboyAvi** [comment]
Hello @parth-verma7 , I want to work on this issue , can you assign it to me.
