### ISSUE TITLE
Polynomial Linear Regression

### ISSUE THREAD

**Issue by RibhavKhanna** [iiitl/ML_tutorial#3]
### Create a .py or .ipynb file and perform Polynomial Linear Regression on SalaryData.csv using sklearn libraries.

**Comment by Zhu-VISH** [comment]
Hi @RibhavKhanna I would like to work on this issue, please assign it to me

**Comment by maskboyAvi** [comment]
Hello @RibhavKhanna ,  I want to work on this issue, can you please assign it to me.

**Comment by parth-verma7** [comment]
@maskboyAvi  I am assigning this issue to you, please start working on it.

**Comment by Dis1309** [comment]
Hi @RibhavKhanna I would like to work on this issue, please assign it to me

**Comment by RibhavKhanna** [comment]
@Dis1309 , @arshkatkar . I am assigning the issue to both of you, only the best one will be accepted and then I am closing this issue as I am seeing a lot of copied code.

**Comment by RibhavKhanna** [comment]
@Dis1309 I have assigned you the issue. Please do not copy the code. try to do it on your own.

**Comment by Dis1309** [comment]
> @Dis1309 I have assigned you the issue. Please do not copy the code. try to do it on your own.
actually sir i had already done the issue in my repository so i just needed to pull request as soon as the assignment was done.
