### ISSUE TITLE
Model Evaluation

### ISSUE THREAD

**Issue by RibhavKhanna** [iiitl/ML_tutorial#4]
### Create a .py or .ipynb file and make a function that takes y_true and y_pred as parameters and gives f1-score,recall ,accuracy and precision of the model.

**Comment by Zhu-VISH** [comment]
Hi @RibhavKhanna I would like to work on this issue, please assign it to me.

**Comment by maskboyAvi** [comment]
Hello @RibhavKhanna , I want to work on this issue, can you please assign it to me.

**Comment by parth-verma7** [comment]
@Zhu-VISH  I am assigning this issue to you
